"""empty message

Revision ID: 5d7c8d1ce38f
Revises: 
Create Date: 2018-09-13 20:13:09.134637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7c8d1ce38f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'DONE', 'ERROR', name='status'), nullable=False),
    sa.Column('status_desc', sa.String(length=255), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_status'), 'website', ['status'], unique=False)
    op.create_index(op.f('ix_website_url'), 'website', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_url'), table_name='website')
    op.drop_index(op.f('ix_website_status'), table_name='website')
    op.drop_table('website')
    # ### end Alembic commands ###
